# -------------------------------
# PVC (Persistent Volume Claim)
# -------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# -------------------------------
# Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "listapro"        # 🔁 ALTERE AQUI: nome do seu banco
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret   # Nome do Secret que você criou
                  key: POSTGRES_USER      # A chave dentro do Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret   # Nome do Secret que você criou
                  key: POSTGRES_PASSWORD     # 🔁 ALTERE AQUI: sua senha do banco
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            #  subPath: postgres-data
            #- name: pg-hba-volume        
            #  mountPath: /etc/postgresql/pg_hba.conf
            #  subPath: pg_hba.conf
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        #- name: pg-hba-volume          
        #  configMap:
        #    name: pg-hba-config


---
# -------------------------------
# Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
