apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapro
  labels:
    app: listapro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listapro
  template:
    metadata:
      labels:
        app: listapro
    spec:
      containers:
        - name: listapro
          image: brunov7/kube-backend:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          ports:
            - containerPort: 8080

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 20

          envFrom:
            - configMapRef:
                name: listapro-config