name: Backend CI/CD com Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Instalar dependências
        run: go mod download

      - name: Executar testes
        run: go test -v ./...

  docker-build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup do Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest

  deploy:
    needs: docker-build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Atualizar imagem Docker
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest

      - name: Parar e remover contêiner atual
        run: |
          sudo docker stop listapro-backend || true
          sudo docker rm listapro-backend || true

      - name: Rodar novo contêiner
        run: |
          sudo docker run -d \
            --name listapro-backend \
            -p 8080:8080 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
            ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest

      - name: Verificar logs
        run: sudo docker logs listapro-backend

      - name: Verificar status
        run: sudo docker ps -a
