name: Backend CI/CD com Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Verificar dependências
        run: go mod download
        
      - name: Executar testes
        run: go test -v ./...
        
  pushParaDockerHub:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest .
        
      - name: Push da imagem Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest
  
  deploy:
    needs: pushParaDockerHub
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Baixar imagem Docker
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest
        
      - name: Parar e remover contêineres existentes
        run: |
          sudo docker stop listapro-backend || true
          sudo docker rm listapro-backend || true
          
      - name: Executar contêineres
        run: |
          sudo docker run -d \
            --name listapro-backend \
            -p 8080:8080 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
            ${{ secrets.DOCKER_USERNAME }}/listapro-backend:latest
            
      - name: Verificar logs do contêiner
        run: sudo docker logs listapro-backend
        
      - name: Verificar status do contêiner
        run: sudo docker ps -a
